let mailHtml = "";

$(document).ready(function(){
	mailHtml += '<html lang="ko">';
	mailHtml += 		'<head>';
	mailHtml += 			'<meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge">';
	mailHtml += 		'</head>';
	mailHtml += 		'<body>';
	mailHtml += 			'<div class="letterbox" style="margin:0 auto; width:38.55%; width: 740px;">';
	mailHtml += 				'<div class="letter-inner" style="padding:40px 20px 110px; background:url(\'/resources/admin/img/email/top_bar.png\') top center/100% no-repeat #f5f5f5;">';
	mailHtml += 					'<header style="margin: 0; height:330px;">';
	mailHtml += 						'<div class="logo-area" style="display:flex; justify-content:space-between; margin-bottom:85px;">';
	mailHtml += 							'<h1><img src="/resources/admin/img/email/logo.png" alt="큐빅아이" /></h1>';
	mailHtml += 							'<span>Your Intelligent eBusiness Partner!</span>';
	mailHtml += 						'</div>';
	mailHtml += 						'<div class="letter-title" style="padding:0 30px; margin-bottom: 60px;">';
	mailHtml += 							'<h2 style="margin-top:40px; line-height: 1.4; font-size: 45px; color: #0e57bf; letter-spacing: -5px;">';
	mailHtml += 								'<span class="b-span" style="display: block;">큐빅아이</span>';
	mailHtml += 								'<span class="b-span" style="font-weight: 600; color: #002e6e;">{TITLE}</span>';
	mailHtml += 							'</h2>';
	mailHtml += 						'</div>';
	mailHtml += 					'</header>';
	mailHtml += 					'<div class="letter-content" style="padding: 0 30px;">';
	mailHtml += 						'<p class="hello" style="margin-bottom:15px; font-size:20px;  color:#0e57bf;">';
	mailHtml += 							'<b>안녕하십니까, {userNm} 회원님</b>';
	mailHtml += 						'</p>';
	mailHtml += 						'<p class="main-text" style="font-size:15px; line-height:1.9; color:#002e6e; word-break:keep-all; letter-spacing:.4px;">';
	mailHtml += 							'{CONTENT1}';
	mailHtml += 						'</p>';
	mailHtml += 					'</div>';
	mailHtml += 					'<div class="table" style="margin-top: 70px; font-size: 15px; color:#002e6e; border-top: 2px solid #002e6e;">';
	mailHtml += 						'<table class="type2">';
	mailHtml += 							'<thead>';
	mailHtml += 								'<tr>';
	mailHtml += 									'<th class="w190" style="height: 50px; line-height: 50px; background-color: #eee; border-right: 1px solid #dee0e4; width: 190px;">{TH}</th>';
	mailHtml += 										'<td style="padding: 0 20px; width:460px; height: 78px; line-height: 78px; text-align: center; font-weight:300; background-color: #f5f5f5;">{TD}</td>';
	mailHtml += 								'</tr>';
	mailHtml += 							'</thead>';
	mailHtml += 						'</table>';
	mailHtml += 					'</div>';
	mailHtml += 					'<p class="main-text" style="font-size:15px; line-height:1.9; color:#002e6e; word-break:keep-all; letter-spacing:.4px;">{CONTENT2}</p>';
	mailHtml += 					'<a class="letter-btn" style="display:block; margin: 60px auto 0; width: 200px; height: 60px; text-align: center; line-height: 60px; font-size: 16px; color: #fff; background-color: #0b53bb; text-decoration:none;" href="https://www.cubici.co.kr/">큐빅아이 바로가기</a>';
	mailHtml += 				'</div>';
	mailHtml += 			'</div>';
	mailHtml += 			'<footer class="letter-footer" style="margin:0 auto; padding: 40px 20px; max-width: 740px; color: #002e6e;">';
	mailHtml += 				'<h5 style="margin-bottom: 20px; font-size: 15px; letter-spacing: .5px;">인공지능 쇼핑몰 통합 지원 서비스 큐빅아이</h5>';
	mailHtml += 				'<address style="display:flex; justify-content:space-between; line-height:1.8; font-size:12px; font-style:normal;">';
	mailHtml += 					'<div>';
	mailHtml += 						'<p class="w400" style="font-weight: 400;">본 메일은 서비스 고지사항 전달 목적의 발신전용 메일로 회신이 불가합니다.</p>';
	mailHtml += 						'<p class="w300" style="font-weight: 300;">(07325) 서울 영등포구 의사당대로 83 오투타워 서울핀테크랩(여의도동) 4층 109호</p>';
		mailHtml += 						'<p class="w300" style="font-weight: 300;"><span>TEL. 02-6925-6373</span><span>MAIL. contact@example.com</span></p>';
	mailHtml += 					'</div>';
	mailHtml += 					'<div>';
	mailHtml += 						'<img src="/resources/admin/img/email/logo.png" alt="큐빅아이">';
	mailHtml += 					'</div>';
	mailHtml += 				'</address>';
	mailHtml += 				'<p class="copyright" style="margin-top: 17px; font-size: 12px; font-weight: 300;">Copyrights CUBICi. ALL RIGHT RESERVED.</p>';
	mailHtml += 			'</footer>';
	mailHtml += 		'</body>';
	mailHtml += 	'</html>';
});
