create table if not exists moneybank_partner (
    firm_no bigserial primary key,
    firm_id varchar(20) not null,
    firm_name varchar(100) not null,
    rep_name varchar(50) not null,
    firm_zip varchar(10),
    firm_address varchar(300) not null,
    manager_name varchar(100),
    manager_rank varchar(50),
    manager_phone varchar(30),
    developer_name varchar(100),
    developer_rank varchar(50),
    developer_phone varchar(30),
    cs_name varchar(100),
    cs_rank varchar(50),
    cs_phone varchar(30),
    firm_tel varchar(30),
    firm_fax varchar(30),
    firm_email varchar(150),
    reg_date timestamp not null default now(),
    update_date timestamp,
    constraint uq_moneybank_partner_identity unique (firm_id, firm_name, rep_name)
);

create table if not exists moneybank_product_preference (
    firm_no bigint primary key references moneybank_partner(firm_no) on delete cascade,
    division varchar(30),
    product_name varchar(100) not null,
    product_status varchar(20) not null default '00',
    min_sales_amount bigint,
    min_business_period varchar(50),
    min_calc_amount bigint,
    credit_rate varchar(50),
    cubici_period varchar(50),
    amount_limit bigint,
    other_conditions varchar(1000),
    service_amount_standard varchar(50),
    service_amount_min bigint,
    service_amount_max bigint,
    service_amount_unit varchar(50),
    execute_amount_standard varchar(50),
    execute_amount_min bigint,
    execute_amount_max bigint,
    execute_amount_unit varchar(50),
    service_fee_standard varchar(50),
    service_fee_min numeric(8, 3),
    service_fee_max numeric(8, 3),
    annual_fee_rate numeric(8, 3),
    interest_standard varchar(50),
    interest_min numeric(8, 3),
    interest_max numeric(8, 3),
    limit_change_yn varchar(1),
    service_repay_period varchar(50),
    service_repay_min integer,
    service_repay_max integer,
    service_repay_method varchar(50),
    extension_yn varchar(1),
    launch_date date,
    expire_date date,
    repayment_count integer,
    repay_amount bigint,
    mid_repay_yn varchar(1),
    b2b_firm_name varchar(100),
    product_type varchar(30),
    reg_date timestamp not null default now(),
    update_date timestamp
);

create index if not exists ix_moneybank_partner_firm_name on moneybank_partner (firm_name);
create index if not exists ix_moneybank_product_name on moneybank_product_preference (product_name);
create index if not exists ix_moneybank_product_status on moneybank_product_preference (product_status);
